<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AuthMicroservice.Sample</RootNamespace>
    <AssemblyName>AuthMicroservice.Sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthMicroservice.Core\AuthMicroservice.Core.csproj" />
    <ProjectReference Include="..\AuthMicroservice.Migrations.InMemory\AuthMicroservice.Migrations.InMemory.csproj" />
    <ProjectReference Include="..\AuthMicroservice.Migrations.Sqlite\AuthMicroservice.Migrations.Sqlite.csproj" />
  </ItemGroup>

</Project>
